import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { GlobalContextProvider } from "@/contexts/GlobalContext";
import { AuthContextProvider } from "@/contexts/AuthContext";
import AuthGuard from "./components/AuthGuard";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${poppins.variable} antialiased`}>
        <GlobalContextProvider>
          <AuthContextProvider>
            <AuthGuard>{children}</AuthGuard>
          </AuthContextProvider>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
